<?php
require __DIR__ . '/config.php';
$page = $_GET['page'] ?? 'dashboard';
$allowed = ['dashboard','plans','plan','analytics','calendar','validate','signatures','memos','programs','competencies','standards','departments','announcements','audit','sitemap'];
if (!in_array($page, $allowed, true)) $page = 'dashboard';
$id = filter_input(INPUT_GET, 'id', FILTER_VALIDATE_INT) ?: 1;
$sem = max(1, min(8, filter_input(INPUT_GET, 'sem', FILTER_VALIDATE_INT) ?: 1));
function e($v) { return htmlspecialchars((string)$v, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function allRows(PDO $db, string $sql, array $params=[]) { $s=$db->prepare($sql); $s->execute($params); return $s->fetchAll(); }
function oneRow(PDO $db, string $sql, array $params=[]) { $s=$db->prepare($sql); $s->execute($params); return $s->fetch() ?: []; }
$stats = [
 'plans'=>(int)$pdo->query('SELECT COUNT(*) FROM curriculums')->fetchColumn(),
 'disciplines'=>(int)$pdo->query('SELECT COUNT(*) FROM curriculum_disciplines')->fetchColumn(),
 'standards'=>(int)$pdo->query('SELECT COUNT(*) FROM standards_fgos')->fetchColumn(),
 'memos'=>(int)$pdo->query('SELECT COUNT(*) FROM service_notes')->fetchColumn(),
];
$title='Сводная панель'; $content='';
if ($page==='dashboard') {
 $title='Сводная панель'; $plans=allRows($pdo,'SELECT c.*, ep.code prog_code, ep.title prog_title FROM curriculums c JOIN educational_programs ep ON ep.id=c.program_id ORDER BY c.id');
 $content='<div class="cards">'; foreach($stats as $k=>$v) $content.='<div class="card"><b>'.e($v).'</b><span>'.e(['plans'=>'Учебные планы','disciplines'=>'Дисциплины','standards'=>'Стандарты ФГОС','memos'=>'Служебные записки'][$k]).'</span></div>'; $content.='</div><h2>Учебные планы</h2><table><tr><th>Программа</th><th>Год</th><th>Статус</th><th></th></tr>'; foreach($plans as $p) $content.='<tr><td>'.e($p['prog_code'].' — '.$p['prog_title']).'</td><td>'.e($p['academic_year']).'</td><td>'.e($p['status']).'</td><td><a href="?page=plan&id='.$p['id'].'">Открыть</a></td></tr>'; $content.='</table>';
} elseif ($page==='plans') {
 $title='Учебные планы'; $rows=allRows($pdo,'SELECT c.*,ep.code,ep.title FROM curriculums c JOIN educational_programs ep ON ep.id=c.program_id ORDER BY c.id'); $content='<h2>Реестр учебных планов</h2><table><tr><th>Код</th><th>Программа</th><th>Год</th><th>Статус</th><th></th></tr>'; foreach($rows as $r) $content.='<tr><td>'.e($r['code']).'</td><td>'.e($r['title']).'</td><td>'.e($r['academic_year']).'</td><td>'.e($r['status']).'</td><td><a href="?page=plan&id='.$r['id'].'">Просмотр</a></td></tr>'; $content.='</table>';
} elseif ($page==='plan') {
 $title='Учебный план'; $p=oneRow($pdo,'SELECT c.*,ep.code,ep.title FROM curriculums c JOIN educational_programs ep ON ep.id=c.program_id WHERE c.id=?',[$id]); $rows=allRows($pdo,'SELECT * FROM curriculum_disciplines WHERE curriculum_id=? AND semester_num=? ORDER BY id',[$id,$sem]); $content='<p><b>'.e($p['code']??'').'</b> '.e($p['title']??'').' · '.e($p['status']??'').'</p><nav class="sem">'; for($i=1;$i<=8;$i++)$content.='<a class="'.($i===$sem?'active':''). '" href="?page=plan&id='.$id.'&sem='.$i.'">Семестр '.$i.'</a>'; $content.='</nav><table><tr><th>Дисциплина</th><th>З.е.</th><th>Часы</th><th>Контроль</th></tr>'; foreach($rows as $r)$content.='<tr><td>'.e($r['discipline_name']).'</td><td>'.e($r['credits_ze']).'</td><td>'.e($r['total_hours']).'</td><td>'.e($r['control_form']).'</td></tr>'; $content.='</table>';
} else {
 $map=['analytics'=>['Аналитика (Chart.js)','SELECT block_type, SUM(credits_ze) AS ze FROM curriculum_disciplines GROUP BY block_type','block_type,ze'],
 'calendar'=>['Календарь дедлайнов (FullCalendar)','SELECT note_num, note_date, status FROM service_notes ORDER BY note_date','note_num,note_date,status'],
 'validate'=>['Экспертиза ФГОС','SELECT * FROM standards_fgos ORDER BY code','code,title,degree_level,total_credits'], 'signatures'=>['Согласование','SELECT * FROM document_signatures ORDER BY step_order','step_order,role_title,status'], 'memos'=>['Служебные записки','SELECT * FROM service_notes ORDER BY id DESC','note_num,note_date,reason,status'], 'programs'=>['Образовательные программы','SELECT * FROM educational_programs ORDER BY id','code,title,level,study_form'], 'competencies'=>['Компетенции','SELECT * FROM competencies ORDER BY code','code,category,title'], 'standards'=>['Стандарты ФГОС','SELECT * FROM standards_fgos ORDER BY code','code,title,degree_level,total_credits'], 'departments'=>['Подразделения','SELECT * FROM departments ORDER BY id','short_name,name,type'], 'announcements'=>['Объявления','SELECT * FROM announcements ORDER BY publish_date DESC','publish_date,title,category'], 'audit'=>['Аудит','SELECT * FROM audit_logs ORDER BY id DESC','event_time,user_name,action,status'], 'sitemap'=>['Карта сайта',null,'']];
 [$title,$sql,$fields]=$map[$page]; if($sql){$rows=allRows($pdo,$sql);$names=array_map('trim',explode(',',$fields));$content='<table><tr>';foreach($names as $n)$content.='<th>'.e($n).'</th>'; $content.='</tr>';foreach($rows as $r){$content.='<tr>';foreach($names as $n)$content.='<td>'.e($r[$n]??'').'</td>'; $content.='</tr>';} $content.='</table>';}else{$content='<p>Разделы: учебные планы, проверка ФГОС, согласование, служебные записки, программы, компетенции, стандарты, подразделения, объявления и аудит.</p>';} }
$nav=['dashboard'=>'Главная','plans'=>'Учебные планы','analytics'=>'Аналитика','calendar'=>'Календарь дедлайнов','validate'=>'Проверка ФГОС','signatures'=>'Согласование','memos'=>'Служебные записки','programs'=>'Программы','competencies'=>'Компетенции','standards'=>'Стандарты','departments'=>'Подразделения','announcements'=>'Объявления','audit'=>'Аудит','sitemap'=>'Карта сайта'];
?><!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> — АНОК</title><style>
body{margin:0;background:#f1f5f9;color:#1e293b;font:14px Arial,sans-serif}header{background:#0f172a;color:#fff;padding:18px 28px}header b{font-size:18px}main{display:flex;min-height:calc(100vh - 60px)}aside{width:220px;background:#1e293b;padding:18px 12px}aside a{display:block;color:#cbd5e1;text-decoration:none;padding:10px;border-radius:6px}aside a:hover,aside a.active{background:#2563eb;color:#fff}section{padding:28px;max-width:1100px;width:100%}h1{margin-top:0}h2{margin-top:26px}table{border-collapse:collapse;background:#fff;width:100%;box-shadow:0 1px 3px #cbd5e1}th,td{text-align:left;padding:11px;border-bottom:1px solid #e2e8f0}th{background:#e2e8f0}a{color:#2563eb}.cards{display:flex;gap:14px;flex-wrap:wrap}.card{background:#fff;padding:20px;min-width:145px;border-radius:8px;box-shadow:0 1px 3px #cbd5e1}.card b,.card span{display:block}.card b{font-size:28px;margin-bottom:8px}.sem{display:flex;gap:5px;flex-wrap:wrap;margin:18px 0}.sem a{padding:8px;background:#e2e8f0;text-decoration:none;border-radius:5px}.sem a.active{background:#2563eb;color:#fff}@media(max-width:700px){aside{width:150px}section{padding:16px}table{font-size:12px}}
</style></head><body><header><b>УНИВЕРСИТЕТ · Центр АНОК</b></header><main><aside><?php foreach($nav as $key=>$label):?><a class="<?=($page===$key?'active':'')?>" href="?page=<?=e($key)?>"><?=e($label)?></a><?php endforeach;?></aside><section><h1><?=e($title)?></h1><?=$content?></section></main></body></html>
